development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://my-fayeserver.herokuapp.com/faye"
  secret_token: "9b0ac78a862c40104decce03d0e4fd643e1313134bf66e3d9a28e4c65faee04c"
  signature_expiration: 86400 # one hour
