development:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
test:
  server: "http://localhost:9292/faye"
  secret_token: "secret"
production:
  server: "https://my-fayeserver.herokuapp.com/faye"
  secret_token: "4e2a9748ea42ca1d773dd6a901c80364e64ecdd672129e7be328580f34886ed0"
  signature_expiration: 86400 # one hour
